### ISSUE TITLE
[OPTIONAL] Detect `--` as the first argument of most builtins and ignore it

### ISSUE THREAD

**Issue by itislu** [LeaYeh/minishell#111]
This applies to the following builtins (all but echo):
- [ ] exit
- [ ] env
- [ ] export
- [ ] unset
- [ ] pwd
- [ ] cd

This is useful because this way one can have an actual argument with the same name as the option, but without using the option.
Example:
If there is a file name `-e`, one might want to cat it, but without the `-e` option:
```sh
cat -- -e
```

Bash manual regarding this topic (last paragraph):
https://www.gnu.org/software/bash/manual/html_node/Shell-Builtin-Commands.html

**Comment by LeaYeh** [comment]
dont do it, your time is worth other more valuable things
