### ISSUE TITLE
[BUG] The exit code when bad substitution happens is not correct yet

### ISSUE THREAD

**Issue by itislu** [LeaYeh/minishell#155]
Bad substitution does not set the exit code atm.

@LeaYeh What do you think, should the expander set the exit code, or whoever is calling the expander?

_Originally posted by @itislu in https://github.com/LeaYeh/minishell/issues/153#issuecomment-1925520553_

**Comment by LeaYeh** [comment]
should be the place which handle Bad substitution error return
