### ISSUE TITLE
[TODO] Add `rl_clear_history()`

### ISSUE THREAD

**Issue by itislu** [LeaYeh/minishell#171]
I saw others use it when they clean their shell. I'm not sure if it would be needed anywhere else.
Vladimir said we should definitely clear the history.

**Comment by LeaYeh** [comment]
When the process terminates, the operating system will reclaim all the memory allocated by the program, including the memory used by readline's history entries. So, from a memory leak perspective within the context of the program's lifetime, not calling rl_clear_history() before exiting won't cause a leak.
