### ISSUE TITLE
[CONCERNING] Collection of test cases that sometimes fail the tester

### ISSUE THREAD

**Issue by itislu** [LeaYeh/minishell#183]
```sh
/bin/echo 42 | /bin/echo 42 && (/bin/echo 42)
```
```sh
/bin/echo 42 | /bin/echo 42 || (/bin/echo 42)
```
```sh
/bin/echo 1 | /bin/echo 2 | /bin/echo 3 && /bin/echo 4 | /bin/echo 5
```
```sh
/bin/echo 1 | /bin/echo 2 | /bin/echo 3 || /bin/echo 4 | /bin/echo 5
```
```sh
(/bin/echo 1 | /bin/echo 2 && ((/bin/echo 3 | /bin/echo 3) | (/bin/echo 4 | /bin/echo 4)))
```

**Comment by LeaYeh** [comment]
Or just print out the different in github action

**Comment by itislu** [comment]
I remember I tried to do that before, and it was not as easy as I thought.
But yes, that would be very helpful.

**Comment by itislu** [comment]
I was able to reproduce the tester inconsistencies.

1. First I modified the tester.sh to only test the 1_operators.sh for the bonus part.

2. When I then run mstest b locally, all tests pass (for the operators), 0 errors.
  I repeated this dozens of times, it never fails.

3. I started the tester with mstest vm.

4. In a new terminal, I started the tester again with mstest b.
  I have to restart it many times, but at some point, there's an error, or two.

5. The more mstest vm I start in yet another new terminal, the more likely it is that mstest b fails in the other terminal.

6. I modified the tester.sh to exit when it detects a difference in the stderror, but before that, to copy all tmp_out and tmp_err 
comparison files for bash and minishell to files with different names.

7. When mstest b fails, I look at the copied diffs and see the following: All outputs come from different commands, most are not even part of the bonus 1_operators.sh.

**My conclusion so far:**
The different instances of the testers running in the Github Actions environment are disturbing each other.
I don't know exactly, but it looks like each job does not run in its completely separate storage space.

**Comment by itislu** [comment]
Oh and I also reproduced it the same way in Codespace.
I was trying to see if the CPU load percentage causes a real difference in the output (Codespace only has 2 cores so it's easier to 100% them) but I could not find an impact.

**Comment by itislu** [comment]
All this is concerning though and should have high priority to fix (I'm already thinking about it, but if you have an idea please help me).
Not only can it result in false negatives, but also false positives.
It makes the regression test worth much less than we thought.
