### ISSUE TITLE
[BUG] Ctrl+D prints too many newlines sometimes

### ISSUE THREAD

**Issue by itislu** [LeaYeh/minishell#186]
It depends on how many instances of minishell are running on top of each other (calling `./minishell` in minishell).
- Ctrl+D in the first instance prints a newline before the exit message.
- Ctrl+D in further instances prints a newline before the exit message and one too much after the exit message.

**Comment by LeaYeh** [comment]
oh you alreadly know it, nice

My opinion is seperate newline and msg
