### ISSUE TITLE
[KNOWN-ISSUE] Order of redirections is wrong for subshells in such a case: `(echo 1 | cat > alt) > out`

### ISSUE THREAD

**Issue by LeaYeh** [LeaYeh/minishell#72]
The output of cat should go to `alt`, not `out`.
#### The order should be: 
First apply the redirections from outside of the subshell, then each command's own redirections.

**Comment by LeaYeh** [comment]
This bug let me consider subshell should has same concept as cmd_table_node. I feel it's must have some way to build the relation to correct the io rediect.
But that also proof how the ast tree import is.

```
    6 command: simple_command
    7        | subshell
    8        | subshell redirect_list
```

Concusion:
I will still try to find a way to fix it before the deadline

**Comment by LeaYeh** [comment]
Record..

```
@LeaYeh ➜ /workspaces/minishell (main) $ bash --posix
bash-5.0$ (echo 1 | cat > alt) > out
bash-5.0$ (echo 1 | cat ) > out
bash-5.0$ (echo 1 | echo 2 ) > out
bash-5.0$ (echo 1 && echo 2 ) > out
bash-5.0$ 

```

**Comment by itislu** [comment]
Another record of a failing test case: 
```sh
ls | (ls | ls | echo 1 && (echo 2) > out1) > out2 && ls
```

**Comment by itislu** [comment]
More test cases:
```sh
(head -1 > file1 | head -1 > file2) < Makefile v
```
```sh
(head -1 > file1 && head -1 > file2) < Makefile 
```
