### ISSUE TITLE
[DISCUSSION] escape char handling in echo

### ISSUE THREAD

**Issue by LeaYeh** [LeaYeh/minishell#81]
https://unix.stackexchange.com/questions/88307/escape-sequences-with-echo-e-in-different-shells

Not sure if we need to implement escape char handling or not

**Comment by itislu** [comment]
I think the escape character `\` should not be handled, as by the subject:
> Not interpret unclosed quotes or special characters which are not required by the subject such as \ (backslash) or ; (semicolon).

Also, this would make it not POSIX compliant, see [here](https://pubs.opengroup.org/onlinepubs/009696799/utilities/echo.html).
